### PR TITLE
Add health check to docker-compose.yml

### PR DESCRIPTION
**Pull request by oleg-fiksel**
Makes sure that the app container is restarted when, for example, an external database is not available.

### CODE REVIEW

**Comment by SISheogorath** [comment]
Can we add this to the container image instead? I think there it's way easier to adopt it for everyone.

**Comment by oleg-fiksel** [comment]
> Can we add this to the container image instead? I think there it's way easier to adopt it for everyone.

In my case I still would need to override the health check because my external DB takes > 5 minutes to start. Add a commented-out health check in the `docker-compose.yml`.
If everyone OK with it I would add another commit for the health check in the Dockerfiles.

**Review by 8ear — COMMENTED** [review]
Why you not add directly also a check for the postgresql DB?

https://github.com/peter-evans/docker-compose-healthcheck

**Comment by davidmehren** [comment]
Since https://github.com/hedgedoc/container/commit/20410f87d5e9753e6e0790ebeb3680549ef7a5e4 the images include a healthcheck. I'd prefer to not add rarely used features to the compose file, so lets close this for now.

**Pull request closed without merging**
