### PR TITLE
Publish nightly docker images

### PR DESCRIPTION
**Pull request by hugopeixoto**
Create and push a docker image based on `hedgedoc/hedgedoc@master` to `quay.io/hedgedoc/hedgedoc:nightly-{alpine,debian}`.

### CODE REVIEW

**Comment by SISheogorath** [comment]
More like a thought than a request: do we want nightly builds in the same image repository as stable ones or do we want to split them?

Here is a rough idea: `quay.io/hedgedoc/hedgedoc-nightly:v20.11.21` as version number (as well as latest). Making it nice to pull any version and keep the stable repository clean. (We might even automate the invalidation of nightly builds.)

**Comment by hugopeixoto** [comment]
> More like a thought than a request: do we want nightly builds in the same image repository as stable ones or do we want to split them?
> 
> Here is a rough idea: `quay.io/hedgedoc/hedgedoc-nightly:v20.11.21` as version number (as well as latest). Making it nice to pull any version and keep the stable repository clean. (We might even automate the invalidation of nightly builds.)

If we want to have versioned nightly image tags (`20201121`, etc), I agree that having them in the main repository would be too noisy and creating a separate one would be a better idea.

I'm not sure if maintaining more than one nightly tag is useful, though. Having one is useful so that folks can test the latest features, but I'm not sure if anyone will be using the images for previous days.

**Comment by SISheogorath** [comment]
Main use-case I can think of is that one runs a nightly, updates and then want to switch back. quay is quite aggressive when it comes to garbage collection. Therefore I would recommend to keep a few around (maybe the last 5 days).

**Comment by hugopeixoto** [comment]
OK, I can change the github action to push to another repo. Instead of `v20.11.21` I think it would be better to use `20201121` or `2020-11-21`, to avoid confusions with semver.

> We might even automate the invalidation of nightly builds

This will require a bit of scripting: using the quay.io API to list all tags and calling DELETE on the ones we want to invalidate. Need to be careful not to expose the secrets in the build logs, and figure out if the current secrets we're using are valid in their API or if we have to create another token. I think I can write this in bash using `date --date="5 day ago" +%y%m%d` and something like `awk '$1 < $CUTOFF'`. I'll probably add this as a separate script in the repository to avoid writing bash inside yaml.

**Comment by hugopeixoto** [comment]
I was having some trouble deleting tags via their API with the robot credentials. Meanwhile, I found out that quay.io supports image invalidation via a LABEL. I'm giving that a try.

**Comment by hugopeixoto** [comment]
I struggled a bit with quay.io, their docs mention `quay.expires.after` and `quay.expires-after` and only the latter works.

It's working now. I created https://quay.io/repository/hedgedoc/hedgedoc-nightly. When this is merged it should start publishing images directly to that repository. Each tag expires in 7 days.

**Comment by SISheogorath** [comment]
Awesome! I see no reason to prevent a merge 👍🏻

**Pull request merged**
